window.sr = ScrollReveal({reset: true })
sr.reveal('.div1',{duration: 2500,reset: true })
sr.reveal('.div2',{duration: 2500,reset: true })
sr.reveal('.div3',{duration: 2500,reset: true })
sr.reveal('.div4',{duration: 2500,reset: true })
sr.reveal('.div5',{duration: 2500,reset: true })
sr.reveal('.div6',{duration: 2500,reset: true })
sr.reveal('.div7',{duration: 2500,reset: true })
sr.reveal('.div8',{duration: 2500,reset: true })
sr.reveal('.div9',{duration: 2500,reset: true })
sr.reveal('.div10',{duration: 2500,reset: true })

